apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ld03
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ld03
    app.kubernetes.io/part-of: ci1t-43256-0074-app
  name: devfile-sample-ld03
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ld03
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ld03
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0074-tenant/ci1t-43256-0074-app/devfile-sample-ld03@sha256:3ac73ca0e8f44565b42f1f523f4f7f08dc3a3bd5e47e0c4b14563ce1d3a9a0dd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
